### ISSUE TITLE
JSON schema and wiki disagree over organisation

### ISSUE THREAD

**Issue by nmtoken** [OrdnanceSurvey/discoverability#1]
The JSON file (https://raw.githubusercontent.com/OrdnanceSurvey/discoverability/master/GC-Data-Catalogue-csv-schema.json) has:

    {
      "name": "Organisation",
      "title": "Organisation",
	  "description": "Short form of Organisation name or Organisation acronym",
      "constraints": {
        "required": true,
        "type": "http://www.w3.org/2001/XMLSchema#string"
      }
    },

but the wiki (https://github.com/OrdnanceSurvey/discoverability/wiki) has:

    Organisation | Mandatory | Organisation name or Organisation acronym.

The wiki description should have **Short form of ** or the JSON should remove **Short form of **

**Comment by PeterParslow** [comment]
Fixed in the JSON
